apiVersion: v1
kind: Service
metadata:
  name: shopping-app-service
spec:
  selector:
    app: shopping-app
  ports:
    - protocol: TCP
      port: 80          # The port that the service will expose
      targetPort: 3000  # The port on which your application is running inside the pod
      nodePort: 30715   # Optional: Specify a custom NodePort (between 30000-32767)
  type: NodePort
