apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopping-app
  template:
    metadata:
      labels:
        app: shopping-app
    spec:
      containers:
      - name: shopping-app
        image: nagenderkalakuntla/shopping:latest
        ports:
        - containerPort: 3000